// Package token generates and hashes the secrets that identify devices.
//
// Two kinds of secret pass through here, both server-generated and both stored
// only as hashes: the single-use enrollment token encoded in a QR code, and the
// long-lived device token an agent puts on every message.
package token

import (
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/hex"
	"fmt"
)

// entropyBytes is the size of a generated token before encoding. 32 bytes is
// well past any brute-force reach, and the tokens are never typed by hand — the
// enrollment one is scanned from a QR code and the device one is stored by the
// agent — so there is no length to economise on.
const entropyBytes = 32

// Generate returns a new random token, URL-safe base64 without padding so it
// survives being put in a URL, a header or a QR payload untouched.
func Generate() (string, error) {
	buf := make([]byte, entropyBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("token: generate: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(buf), nil
}

// Hasher turns a plaintext token into the value stored in the database.
type Hasher interface {
	Hash(token string) string
}

// SHA256 hashes with a plain SHA-256.
//
// A plain hash rather than a password KDF (bcrypt, argon2) on purpose: these
// are 32 random bytes generated by the server, not human-chosen secrets, so
// there is no dictionary to attack and no work factor worth paying. The reason
// for hashing at all is that a database dump must not hand over the fleet, and
// preimage resistance over a high-entropy input is enough for that. It also has
// to be fast: device tokens are verified on every message of every stream.
type SHA256 struct{}

// Hash returns the hex-encoded SHA-256 of the token.
func (SHA256) Hash(token string) string {
	sum := sha256.Sum256([]byte(token))
	return hex.EncodeToString(sum[:])
}

// Equal compares two hashes in constant time.
//
// Timing here is a much weaker concern than in a password check — the compared
// values are hashes, not the secrets themselves, so a timing leak reveals
// digest bytes rather than token bytes — but the constant-time compare costs
// nothing and removes the need to reason about it.
func Equal(a, b string) bool {
	return subtle.ConstantTimeCompare([]byte(a), []byte(b)) == 1
}
