package grpcserver

import (
	"crypto/sha256"
	"encoding/hex"
)

// SHA256Hasher hashes tokens with a plain SHA-256.
//
// A plain hash rather than a password KDF (bcrypt, argon2) on purpose: device
// tokens are long random values generated by the server, not human-chosen
// secrets, so there is no dictionary to attack and no work factor worth paying.
// The reason for hashing at all is that a database dump must not hand over the
// fleet — and for that, a preimage-resistant hash of a high-entropy value is
// enough. It also has to be fast: this runs on every message of every stream.
type SHA256Hasher struct{}

// Hash returns the hex-encoded SHA-256 of the token.
func (SHA256Hasher) Hash(token string) string {
	sum := sha256.Sum256([]byte(token))
	return hex.EncodeToString(sum[:])
}
